/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db;


import io.github.yusufsdiscordbot.mystiguardian.db.tables.FlywaySchemaHistory;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.StoredFiles;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_STORED_FILES_FILE_NAME = Internal.createIndex(DSL.name("idx_stored_files_file_name"), StoredFiles.STORED_FILES, new OrderField[] { StoredFiles.STORED_FILES.FILE_NAME }, false);
    public static final Index IDX_STORED_FILES_GUILD_ID = Internal.createIndex(DSL.name("idx_stored_files_guild_id"), StoredFiles.STORED_FILES, new OrderField[] { StoredFiles.STORED_FILES.GUILD_ID }, false);
}
