/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db;


import io.github.yusufsdiscordbot.mystiguardian.db.tables.AmountOfBans;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.AmountOfKicks;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.AmountOfTimeOuts;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.AmountOfWarns;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.AuditChannel;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.Ban;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.FlywaySchemaHistory;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.Kick;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.Oauth;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.ReloadAudit;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.SoftBan;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.StoredFiles;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.TimeOut;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.Warns;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.amount_of_bans</code>.
     */
    public final AmountOfBans AMOUNT_OF_BANS = AmountOfBans.AMOUNT_OF_BANS;

    /**
     * The table <code>public.amount_of_kicks</code>.
     */
    public final AmountOfKicks AMOUNT_OF_KICKS = AmountOfKicks.AMOUNT_OF_KICKS;

    /**
     * The table <code>public.amount_of_time_outs</code>.
     */
    public final AmountOfTimeOuts AMOUNT_OF_TIME_OUTS = AmountOfTimeOuts.AMOUNT_OF_TIME_OUTS;

    /**
     * The table <code>public.amount_of_warns</code>.
     */
    public final AmountOfWarns AMOUNT_OF_WARNS = AmountOfWarns.AMOUNT_OF_WARNS;

    /**
     * The table <code>public.audit_channel</code>.
     */
    public final AuditChannel AUDIT_CHANNEL = AuditChannel.AUDIT_CHANNEL;

    /**
     * The table <code>public.ban</code>.
     */
    public final Ban BAN = Ban.BAN;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.kick</code>.
     */
    public final Kick KICK = Kick.KICK;

    /**
     * The table <code>public.oauth</code>.
     */
    public final Oauth OAUTH = Oauth.OAUTH;

    /**
     * The table <code>public.reload_audit</code>.
     */
    public final ReloadAudit RELOAD_AUDIT = ReloadAudit.RELOAD_AUDIT;

    /**
     * The table <code>public.soft_ban</code>.
     */
    public final SoftBan SOFT_BAN = SoftBan.SOFT_BAN;

    /**
     * The table <code>public.stored_files</code>.
     */
    public final StoredFiles STORED_FILES = StoredFiles.STORED_FILES;

    /**
     * The table <code>public.time_out</code>.
     */
    public final TimeOut TIME_OUT = TimeOut.TIME_OUT;

    /**
     * The table <code>public.warns</code>.
     */
    public final Warns WARNS = Warns.WARNS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AmountOfBans.AMOUNT_OF_BANS,
            AmountOfKicks.AMOUNT_OF_KICKS,
            AmountOfTimeOuts.AMOUNT_OF_TIME_OUTS,
            AmountOfWarns.AMOUNT_OF_WARNS,
            AuditChannel.AUDIT_CHANNEL,
            Ban.BAN,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Kick.KICK,
            Oauth.OAUTH,
            ReloadAudit.RELOAD_AUDIT,
            SoftBan.SOFT_BAN,
            StoredFiles.STORED_FILES,
            TimeOut.TIME_OUT,
            Warns.WARNS
        );
    }
}
