/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.AmountOfWarnsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmountOfWarns extends TableImpl<AmountOfWarnsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.amount_of_warns</code>
     */
    public static final AmountOfWarns AMOUNT_OF_WARNS = new AmountOfWarns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmountOfWarnsRecord> getRecordType() {
        return AmountOfWarnsRecord.class;
    }

    /**
     * The column <code>public.amount_of_warns.id</code>.
     */
    public final TableField<AmountOfWarnsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.amount_of_warns.guild_id</code>.
     */
    public final TableField<AmountOfWarnsRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.amount_of_warns.user_id</code>.
     */
    public final TableField<AmountOfWarnsRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.amount_of_warns.amount_of_warns</code>.
     */
    public final TableField<AmountOfWarnsRecord, Integer> AMOUNT_OF_WARNS_ = createField(DSL.name("amount_of_warns"), SQLDataType.INTEGER.nullable(false), this, "");

    private AmountOfWarns(Name alias, Table<AmountOfWarnsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AmountOfWarns(Name alias, Table<AmountOfWarnsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.amount_of_warns</code> table reference
     */
    public AmountOfWarns(String alias) {
        this(DSL.name(alias), AMOUNT_OF_WARNS);
    }

    /**
     * Create an aliased <code>public.amount_of_warns</code> table reference
     */
    public AmountOfWarns(Name alias) {
        this(alias, AMOUNT_OF_WARNS);
    }

    /**
     * Create a <code>public.amount_of_warns</code> table reference
     */
    public AmountOfWarns() {
        this(DSL.name("amount_of_warns"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AmountOfWarnsRecord, Long> getIdentity() {
        return (Identity<AmountOfWarnsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AmountOfWarnsRecord> getPrimaryKey() {
        return Keys.AMOUNT_OF_WARNS_PKEY;
    }

    @Override
    public List<UniqueKey<AmountOfWarnsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AMOUNT_OF_WARNS_GUILD_ID_USER_ID_ID_KEY);
    }

    @Override
    public AmountOfWarns as(String alias) {
        return new AmountOfWarns(DSL.name(alias), this);
    }

    @Override
    public AmountOfWarns as(Name alias) {
        return new AmountOfWarns(alias, this);
    }

    @Override
    public AmountOfWarns as(Table<?> alias) {
        return new AmountOfWarns(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfWarns rename(String name) {
        return new AmountOfWarns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfWarns rename(Name name) {
        return new AmountOfWarns(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfWarns rename(Table<?> name) {
        return new AmountOfWarns(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfWarns where(Condition condition) {
        return new AmountOfWarns(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfWarns where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfWarns where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfWarns where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfWarns where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfWarns where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfWarns where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfWarns where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfWarns whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfWarns whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
