/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.AmountOfTimeOutsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmountOfTimeOuts extends TableImpl<AmountOfTimeOutsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.amount_of_time_outs</code>
     */
    public static final AmountOfTimeOuts AMOUNT_OF_TIME_OUTS = new AmountOfTimeOuts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmountOfTimeOutsRecord> getRecordType() {
        return AmountOfTimeOutsRecord.class;
    }

    /**
     * The column <code>public.amount_of_time_outs.id</code>.
     */
    public final TableField<AmountOfTimeOutsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.amount_of_time_outs.guild_id</code>.
     */
    public final TableField<AmountOfTimeOutsRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.amount_of_time_outs.user_id</code>.
     */
    public final TableField<AmountOfTimeOutsRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.amount_of_time_outs.amount_of_time_outs</code>.
     */
    public final TableField<AmountOfTimeOutsRecord, Integer> AMOUNT_OF_TIME_OUTS_ = createField(DSL.name("amount_of_time_outs"), SQLDataType.INTEGER.nullable(false), this, "");

    private AmountOfTimeOuts(Name alias, Table<AmountOfTimeOutsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AmountOfTimeOuts(Name alias, Table<AmountOfTimeOutsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.amount_of_time_outs</code> table reference
     */
    public AmountOfTimeOuts(String alias) {
        this(DSL.name(alias), AMOUNT_OF_TIME_OUTS);
    }

    /**
     * Create an aliased <code>public.amount_of_time_outs</code> table reference
     */
    public AmountOfTimeOuts(Name alias) {
        this(alias, AMOUNT_OF_TIME_OUTS);
    }

    /**
     * Create a <code>public.amount_of_time_outs</code> table reference
     */
    public AmountOfTimeOuts() {
        this(DSL.name("amount_of_time_outs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AmountOfTimeOutsRecord, Long> getIdentity() {
        return (Identity<AmountOfTimeOutsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AmountOfTimeOutsRecord> getPrimaryKey() {
        return Keys.AMOUNT_OF_TIME_OUTS_PKEY;
    }

    @Override
    public List<UniqueKey<AmountOfTimeOutsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AMOUNT_OF_TIME_OUTS_GUILD_ID_USER_ID_ID_KEY);
    }

    @Override
    public AmountOfTimeOuts as(String alias) {
        return new AmountOfTimeOuts(DSL.name(alias), this);
    }

    @Override
    public AmountOfTimeOuts as(Name alias) {
        return new AmountOfTimeOuts(alias, this);
    }

    @Override
    public AmountOfTimeOuts as(Table<?> alias) {
        return new AmountOfTimeOuts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfTimeOuts rename(String name) {
        return new AmountOfTimeOuts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfTimeOuts rename(Name name) {
        return new AmountOfTimeOuts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfTimeOuts rename(Table<?> name) {
        return new AmountOfTimeOuts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfTimeOuts where(Condition condition) {
        return new AmountOfTimeOuts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfTimeOuts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfTimeOuts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfTimeOuts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfTimeOuts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfTimeOuts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfTimeOuts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfTimeOuts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfTimeOuts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfTimeOuts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
