/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.AmountOfBansRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmountOfBans extends TableImpl<AmountOfBansRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.amount_of_bans</code>
     */
    public static final AmountOfBans AMOUNT_OF_BANS = new AmountOfBans();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmountOfBansRecord> getRecordType() {
        return AmountOfBansRecord.class;
    }

    /**
     * The column <code>public.amount_of_bans.id</code>.
     */
    public final TableField<AmountOfBansRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.amount_of_bans.guild_id</code>.
     */
    public final TableField<AmountOfBansRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.amount_of_bans.user_id</code>.
     */
    public final TableField<AmountOfBansRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.amount_of_bans.amount_of_bans</code>.
     */
    public final TableField<AmountOfBansRecord, Integer> AMOUNT_OF_BANS_ = createField(DSL.name("amount_of_bans"), SQLDataType.INTEGER.nullable(false), this, "");

    private AmountOfBans(Name alias, Table<AmountOfBansRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AmountOfBans(Name alias, Table<AmountOfBansRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.amount_of_bans</code> table reference
     */
    public AmountOfBans(String alias) {
        this(DSL.name(alias), AMOUNT_OF_BANS);
    }

    /**
     * Create an aliased <code>public.amount_of_bans</code> table reference
     */
    public AmountOfBans(Name alias) {
        this(alias, AMOUNT_OF_BANS);
    }

    /**
     * Create a <code>public.amount_of_bans</code> table reference
     */
    public AmountOfBans() {
        this(DSL.name("amount_of_bans"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AmountOfBansRecord, Long> getIdentity() {
        return (Identity<AmountOfBansRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AmountOfBansRecord> getPrimaryKey() {
        return Keys.AMOUNT_OF_BANS_PKEY;
    }

    @Override
    public List<UniqueKey<AmountOfBansRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AMOUNT_OF_BANS_GUILD_ID_USER_ID_ID_KEY);
    }

    @Override
    public AmountOfBans as(String alias) {
        return new AmountOfBans(DSL.name(alias), this);
    }

    @Override
    public AmountOfBans as(Name alias) {
        return new AmountOfBans(alias, this);
    }

    @Override
    public AmountOfBans as(Table<?> alias) {
        return new AmountOfBans(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfBans rename(String name) {
        return new AmountOfBans(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfBans rename(Name name) {
        return new AmountOfBans(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfBans rename(Table<?> name) {
        return new AmountOfBans(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfBans where(Condition condition) {
        return new AmountOfBans(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfBans where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfBans where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfBans where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfBans where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfBans where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfBans where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmountOfBans where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfBans whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmountOfBans whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
