/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.KickRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Kick extends TableImpl<KickRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.kick</code>
     */
    public static final Kick KICK = new Kick();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KickRecord> getRecordType() {
        return KickRecord.class;
    }

    /**
     * The column <code>public.kick.id</code>.
     */
    public final TableField<KickRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.kick.guild_id</code>.
     */
    public final TableField<KickRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.kick.user_id</code>.
     */
    public final TableField<KickRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.kick.reason</code>.
     */
    public final TableField<KickRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.kick.time</code>.
     */
    public final TableField<KickRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    private Kick(Name alias, Table<KickRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Kick(Name alias, Table<KickRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.kick</code> table reference
     */
    public Kick(String alias) {
        this(DSL.name(alias), KICK);
    }

    /**
     * Create an aliased <code>public.kick</code> table reference
     */
    public Kick(Name alias) {
        this(alias, KICK);
    }

    /**
     * Create a <code>public.kick</code> table reference
     */
    public Kick() {
        this(DSL.name("kick"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<KickRecord, Long> getIdentity() {
        return (Identity<KickRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<KickRecord> getPrimaryKey() {
        return Keys.KICK_PKEY;
    }

    @Override
    public List<UniqueKey<KickRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KICK_GUILD_ID_USER_ID_ID_KEY);
    }

    @Override
    public Kick as(String alias) {
        return new Kick(DSL.name(alias), this);
    }

    @Override
    public Kick as(Name alias) {
        return new Kick(alias, this);
    }

    @Override
    public Kick as(Table<?> alias) {
        return new Kick(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Kick rename(String name) {
        return new Kick(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Kick rename(Name name) {
        return new Kick(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Kick rename(Table<?> name) {
        return new Kick(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Kick where(Condition condition) {
        return new Kick(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Kick where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Kick where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Kick where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Kick where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Kick where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Kick where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Kick where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Kick whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Kick whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super String, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super String, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
