/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.ReloadAuditRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReloadAudit extends TableImpl<ReloadAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.reload_audit</code>
     */
    public static final ReloadAudit RELOAD_AUDIT = new ReloadAudit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReloadAuditRecord> getRecordType() {
        return ReloadAuditRecord.class;
    }

    /**
     * The column <code>public.reload_audit.id</code>.
     */
    public final TableField<ReloadAuditRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.reload_audit.user_id</code>.
     */
    public final TableField<ReloadAuditRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.reload_audit.reason</code>.
     */
    public final TableField<ReloadAuditRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.reload_audit.time</code>.
     */
    public final TableField<ReloadAuditRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    private ReloadAudit(Name alias, Table<ReloadAuditRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReloadAudit(Name alias, Table<ReloadAuditRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.reload_audit</code> table reference
     */
    public ReloadAudit(String alias) {
        this(DSL.name(alias), RELOAD_AUDIT);
    }

    /**
     * Create an aliased <code>public.reload_audit</code> table reference
     */
    public ReloadAudit(Name alias) {
        this(alias, RELOAD_AUDIT);
    }

    /**
     * Create a <code>public.reload_audit</code> table reference
     */
    public ReloadAudit() {
        this(DSL.name("reload_audit"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ReloadAuditRecord, Long> getIdentity() {
        return (Identity<ReloadAuditRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReloadAuditRecord> getPrimaryKey() {
        return Keys.RELOAD_AUDIT_PKEY;
    }

    @Override
    public ReloadAudit as(String alias) {
        return new ReloadAudit(DSL.name(alias), this);
    }

    @Override
    public ReloadAudit as(Name alias) {
        return new ReloadAudit(alias, this);
    }

    @Override
    public ReloadAudit as(Table<?> alias) {
        return new ReloadAudit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReloadAudit rename(String name) {
        return new ReloadAudit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReloadAudit rename(Name name) {
        return new ReloadAudit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReloadAudit rename(Table<?> name) {
        return new ReloadAudit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReloadAudit where(Condition condition) {
        return new ReloadAudit(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReloadAudit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReloadAudit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReloadAudit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReloadAudit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReloadAudit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReloadAudit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReloadAudit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReloadAudit whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReloadAudit whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
