/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.SoftBanRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SoftBan extends TableImpl<SoftBanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.soft_ban</code>
     */
    public static final SoftBan SOFT_BAN = new SoftBan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SoftBanRecord> getRecordType() {
        return SoftBanRecord.class;
    }

    /**
     * The column <code>public.soft_ban.id</code>.
     */
    public final TableField<SoftBanRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.soft_ban.guild_id</code>.
     */
    public final TableField<SoftBanRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.soft_ban.user_id</code>.
     */
    public final TableField<SoftBanRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.soft_ban.reason</code>.
     */
    public final TableField<SoftBanRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.soft_ban.days</code>.
     */
    public final TableField<SoftBanRecord, Integer> DAYS = createField(DSL.name("days"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.soft_ban.time</code>.
     */
    public final TableField<SoftBanRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    private SoftBan(Name alias, Table<SoftBanRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SoftBan(Name alias, Table<SoftBanRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.soft_ban</code> table reference
     */
    public SoftBan(String alias) {
        this(DSL.name(alias), SOFT_BAN);
    }

    /**
     * Create an aliased <code>public.soft_ban</code> table reference
     */
    public SoftBan(Name alias) {
        this(alias, SOFT_BAN);
    }

    /**
     * Create a <code>public.soft_ban</code> table reference
     */
    public SoftBan() {
        this(DSL.name("soft_ban"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SoftBanRecord, Long> getIdentity() {
        return (Identity<SoftBanRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SoftBanRecord> getPrimaryKey() {
        return Keys.SOFT_BAN_PKEY;
    }

    @Override
    public SoftBan as(String alias) {
        return new SoftBan(DSL.name(alias), this);
    }

    @Override
    public SoftBan as(Name alias) {
        return new SoftBan(alias, this);
    }

    @Override
    public SoftBan as(Table<?> alias) {
        return new SoftBan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SoftBan rename(String name) {
        return new SoftBan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SoftBan rename(Name name) {
        return new SoftBan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SoftBan rename(Table<?> name) {
        return new SoftBan(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SoftBan where(Condition condition) {
        return new SoftBan(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SoftBan where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SoftBan where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SoftBan where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SoftBan where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SoftBan where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SoftBan where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SoftBan where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SoftBan whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SoftBan whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Integer, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super String, ? super String, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super String, ? super String, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
