/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Indexes;
import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.StoredFilesRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoredFiles extends TableImpl<StoredFilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.stored_files</code>
     */
    public static final StoredFiles STORED_FILES = new StoredFiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoredFilesRecord> getRecordType() {
        return StoredFilesRecord.class;
    }

    /**
     * The column <code>public.stored_files.id</code>.
     */
    public final TableField<StoredFilesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.stored_files.guild_id</code>.
     */
    public final TableField<StoredFilesRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.stored_files.file_name</code>.
     */
    public final TableField<StoredFilesRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.stored_files.file_type</code>.
     */
    public final TableField<StoredFilesRecord, String> FILE_TYPE = createField(DSL.name("file_type"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.stored_files.description</code>.
     */
    public final TableField<StoredFilesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.stored_files.file_url</code>.
     */
    public final TableField<StoredFilesRecord, String> FILE_URL = createField(DSL.name("file_url"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * The column <code>public.stored_files.uploaded_by</code>.
     */
    public final TableField<StoredFilesRecord, String> UPLOADED_BY = createField(DSL.name("uploaded_by"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.stored_files.uploaded_at</code>.
     */
    public final TableField<StoredFilesRecord, OffsetDateTime> UPLOADED_AT = createField(DSL.name("uploaded_at"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    private StoredFiles(Name alias, Table<StoredFilesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StoredFiles(Name alias, Table<StoredFilesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.stored_files</code> table reference
     */
    public StoredFiles(String alias) {
        this(DSL.name(alias), STORED_FILES);
    }

    /**
     * Create an aliased <code>public.stored_files</code> table reference
     */
    public StoredFiles(Name alias) {
        this(alias, STORED_FILES);
    }

    /**
     * Create a <code>public.stored_files</code> table reference
     */
    public StoredFiles() {
        this(DSL.name("stored_files"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_STORED_FILES_FILE_NAME, Indexes.IDX_STORED_FILES_GUILD_ID);
    }

    @Override
    public Identity<StoredFilesRecord, Long> getIdentity() {
        return (Identity<StoredFilesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoredFilesRecord> getPrimaryKey() {
        return Keys.STORED_FILES_PKEY;
    }

    @Override
    public List<UniqueKey<StoredFilesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.STORED_FILES_GUILD_ID_FILE_NAME_KEY);
    }

    @Override
    public StoredFiles as(String alias) {
        return new StoredFiles(DSL.name(alias), this);
    }

    @Override
    public StoredFiles as(Name alias) {
        return new StoredFiles(alias, this);
    }

    @Override
    public StoredFiles as(Table<?> alias) {
        return new StoredFiles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoredFiles rename(String name) {
        return new StoredFiles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoredFiles rename(Name name) {
        return new StoredFiles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoredFiles rename(Table<?> name) {
        return new StoredFiles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoredFiles where(Condition condition) {
        return new StoredFiles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoredFiles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoredFiles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoredFiles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoredFiles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoredFiles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoredFiles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoredFiles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoredFiles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoredFiles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, String, String, String, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
