/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables;


import io.github.yusufsdiscordbot.mystiguardian.db.Keys;
import io.github.yusufsdiscordbot.mystiguardian.db.Public;
import io.github.yusufsdiscordbot.mystiguardian.db.tables.records.TimeOutRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TimeOut extends TableImpl<TimeOutRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.time_out</code>
     */
    public static final TimeOut TIME_OUT = new TimeOut();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TimeOutRecord> getRecordType() {
        return TimeOutRecord.class;
    }

    /**
     * The column <code>public.time_out.id</code>.
     */
    public final TableField<TimeOutRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.time_out.guild_id</code>.
     */
    public final TableField<TimeOutRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.time_out.user_id</code>.
     */
    public final TableField<TimeOutRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.time_out.reason</code>.
     */
    public final TableField<TimeOutRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.time_out.duration</code>.
     */
    public final TableField<TimeOutRecord, OffsetDateTime> DURATION = createField(DSL.name("duration"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    /**
     * The column <code>public.time_out.time</code>.
     */
    public final TableField<TimeOutRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    private TimeOut(Name alias, Table<TimeOutRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TimeOut(Name alias, Table<TimeOutRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.time_out</code> table reference
     */
    public TimeOut(String alias) {
        this(DSL.name(alias), TIME_OUT);
    }

    /**
     * Create an aliased <code>public.time_out</code> table reference
     */
    public TimeOut(Name alias) {
        this(alias, TIME_OUT);
    }

    /**
     * Create a <code>public.time_out</code> table reference
     */
    public TimeOut() {
        this(DSL.name("time_out"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TimeOutRecord, Long> getIdentity() {
        return (Identity<TimeOutRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TimeOutRecord> getPrimaryKey() {
        return Keys.TIME_OUT_PKEY;
    }

    @Override
    public List<UniqueKey<TimeOutRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TIME_OUT_GUILD_ID_USER_ID_ID_KEY);
    }

    @Override
    public TimeOut as(String alias) {
        return new TimeOut(DSL.name(alias), this);
    }

    @Override
    public TimeOut as(Name alias) {
        return new TimeOut(alias, this);
    }

    @Override
    public TimeOut as(Table<?> alias) {
        return new TimeOut(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeOut rename(String name) {
        return new TimeOut(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeOut rename(Name name) {
        return new TimeOut(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeOut rename(Table<?> name) {
        return new TimeOut(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TimeOut where(Condition condition) {
        return new TimeOut(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TimeOut where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TimeOut where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TimeOut where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TimeOut where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TimeOut where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TimeOut where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TimeOut where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TimeOut whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TimeOut whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super String, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super String, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
