/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables.records;


import io.github.yusufsdiscordbot.mystigurdian.db.tables.Auth;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthRecord extends UpdatableRecordImpl<AuthRecord> implements Record5<String, String, Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.auth.access_token</code>.
     */
    public AuthRecord setAccessToken(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.auth.access_token</code>.
     */
    public String getAccessToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.auth.refresh_token</code>.
     */
    public AuthRecord setRefreshToken(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.auth.refresh_token</code>.
     */
    public String getRefreshToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.auth.expires_at</code>.
     */
    public AuthRecord setExpiresAt(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.auth.expires_at</code>.
     */
    public Long getExpiresAt() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.auth.user_id</code>.
     */
    public AuthRecord setUserId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.auth.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.auth.id</code>.
     */
    public AuthRecord setId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.auth.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, Long, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, Long, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Auth.AUTH.ACCESS_TOKEN;
    }

    @Override
    public Field<String> field2() {
        return Auth.AUTH.REFRESH_TOKEN;
    }

    @Override
    public Field<Long> field3() {
        return Auth.AUTH.EXPIRES_AT;
    }

    @Override
    public Field<String> field4() {
        return Auth.AUTH.USER_ID;
    }

    @Override
    public Field<Long> field5() {
        return Auth.AUTH.ID;
    }

    @Override
    public String component1() {
        return getAccessToken();
    }

    @Override
    public String component2() {
        return getRefreshToken();
    }

    @Override
    public Long component3() {
        return getExpiresAt();
    }

    @Override
    public String component4() {
        return getUserId();
    }

    @Override
    public Long component5() {
        return getId();
    }

    @Override
    public String value1() {
        return getAccessToken();
    }

    @Override
    public String value2() {
        return getRefreshToken();
    }

    @Override
    public Long value3() {
        return getExpiresAt();
    }

    @Override
    public String value4() {
        return getUserId();
    }

    @Override
    public Long value5() {
        return getId();
    }

    @Override
    public AuthRecord value1(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public AuthRecord value2(String value) {
        setRefreshToken(value);
        return this;
    }

    @Override
    public AuthRecord value3(Long value) {
        setExpiresAt(value);
        return this;
    }

    @Override
    public AuthRecord value4(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public AuthRecord value5(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AuthRecord values(String value1, String value2, Long value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthRecord
     */
    public AuthRecord() {
        super(Auth.AUTH);
    }

    /**
     * Create a detached, initialised AuthRecord
     */
    public AuthRecord(String accessToken, String refreshToken, Long expiresAt, String userId, Long id) {
        super(Auth.AUTH);

        setAccessToken(accessToken);
        setRefreshToken(refreshToken);
        setExpiresAt(expiresAt);
        setUserId(userId);
        setId(id);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AuthRecord
     */
    public AuthRecord(io.github.yusufsdiscordbot.mystigurdian.db.tables.pojos.Auth value) {
        super(Auth.AUTH);

        if (value != null) {
            setAccessToken(value.getAccessToken());
            setRefreshToken(value.getRefreshToken());
            setExpiresAt(value.getExpiresAt());
            setUserId(value.getUserId());
            setId(value.getId());
            resetChangedOnNotNull();
        }
    }
}
