/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables.records;


import io.github.yusufsdiscordbot.mystigurdian.db.tables.Kick;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class KickRecord extends TableRecordImpl<KickRecord> implements Record5<String, String, String, Long, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached KickRecord
     */
    public KickRecord() {
        super(Kick.KICK);
    }

    /**
     * Create a detached, initialised KickRecord
     */
    public KickRecord(String reason, String userId, String guildId, Long id, OffsetDateTime time) {
        super(Kick.KICK);

        setReason(reason);
        setUserId(userId);
        setGuildId(guildId);
        setId(id);
        setTime(time);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised KickRecord
     */
    public KickRecord(io.github.yusufsdiscordbot.mystigurdian.db.tables.pojos.Kick value) {
        super(Kick.KICK);

        if (value != null) {
            setReason(value.getReason());
            setUserId(value.getUserId());
            setGuildId(value.getGuildId());
            setId(value.getId());
            setTime(value.getTime());
            resetChangedOnNotNull();
        }
    }

    /**
     * Getter for <code>public.kick.reason</code>.
     */
    public String getReason() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.kick.reason</code>.
     */
    public KickRecord setReason(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.kick.user_id</code>.
     */
    public KickRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.kick.guild_id</code>.
     */
    public KickRecord setGuildId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>public.kick.id</code>.
     */
    public KickRecord setId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.kick.time</code>.
     */
    public KickRecord setTime(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    @Override
    public Row5<String, String, String, Long, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, Long, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Kick.KICK.REASON;
    }

    @Override
    public Field<String> field2() {
        return Kick.KICK.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Kick.KICK.GUILD_ID;
    }

    @Override
    public Field<Long> field4() {
        return Kick.KICK.ID;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Kick.KICK.TIME;
    }

    @Override
    public String component1() {
        return getReason();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getGuildId();
    }

    @Override
    public Long component4() {
        return getId();
    }

    @Override
    public OffsetDateTime component5() {
        return getTime();
    }

    @Override
    public String value1() {
        return getReason();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getGuildId();
    }

    @Override
    public Long value4() {
        return getId();
    }

    @Override
    public OffsetDateTime value5() {
        return getTime();
    }

    @Override
    public KickRecord value1(String value) {
        setReason(value);
        return this;
    }

    @Override
    public KickRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public KickRecord value3(String value) {
        setGuildId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public KickRecord value4(Long value) {
        setId(value);
        return this;
    }

    @Override
    public KickRecord value5(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public KickRecord values(String value1, String value2, String value3, Long value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
