/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables.records;


import io.github.yusufsdiscordbot.mystigurdian.db.tables.TimeOut;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TimeOutRecord extends TableRecordImpl<TimeOutRecord> implements Record6<OffsetDateTime, String, String, String, Long, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached TimeOutRecord
     */
    public TimeOutRecord() {
        super(TimeOut.TIME_OUT);
    }

    /**
     * Create a detached, initialised TimeOutRecord
     */
    public TimeOutRecord(OffsetDateTime duration, String reason, String userId, String guildId, Long id, OffsetDateTime time) {
        super(TimeOut.TIME_OUT);

        setDuration(duration);
        setReason(reason);
        setUserId(userId);
        setGuildId(guildId);
        setId(id);
        setTime(time);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TimeOutRecord
     */
    public TimeOutRecord(io.github.yusufsdiscordbot.mystigurdian.db.tables.pojos.TimeOut value) {
        super(TimeOut.TIME_OUT);

        if (value != null) {
            setDuration(value.getDuration());
            setReason(value.getReason());
            setUserId(value.getUserId());
            setGuildId(value.getGuildId());
            setId(value.getId());
            setTime(value.getTime());
            resetChangedOnNotNull();
        }
    }

    /**
     * Getter for <code>public.time_out.duration</code>.
     */
    public OffsetDateTime getDuration() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.time_out.duration</code>.
     */
    public TimeOutRecord setDuration(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.time_out.reason</code>.
     */
    public String getReason() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.time_out.reason</code>.
     */
    public TimeOutRecord setReason(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.time_out.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.time_out.user_id</code>.
     */
    public TimeOutRecord setUserId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.time_out.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.time_out.guild_id</code>.
     */
    public TimeOutRecord setGuildId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.time_out.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>public.time_out.id</code>.
     */
    public TimeOutRecord setId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.time_out.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.time_out.time</code>.
     */
    public TimeOutRecord setTime(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    @Override
    public Row6<OffsetDateTime, String, String, String, Long, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<OffsetDateTime, String, String, String, Long, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<OffsetDateTime> field1() {
        return TimeOut.TIME_OUT.DURATION;
    }

    @Override
    public Field<String> field2() {
        return TimeOut.TIME_OUT.REASON;
    }

    @Override
    public Field<String> field3() {
        return TimeOut.TIME_OUT.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return TimeOut.TIME_OUT.GUILD_ID;
    }

    @Override
    public Field<Long> field5() {
        return TimeOut.TIME_OUT.ID;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return TimeOut.TIME_OUT.TIME;
    }

    @Override
    public OffsetDateTime component1() {
        return getDuration();
    }

    @Override
    public String component2() {
        return getReason();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getGuildId();
    }

    @Override
    public Long component5() {
        return getId();
    }

    @Override
    public OffsetDateTime component6() {
        return getTime();
    }

    @Override
    public OffsetDateTime value1() {
        return getDuration();
    }

    @Override
    public String value2() {
        return getReason();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getGuildId();
    }

    @Override
    public Long value5() {
        return getId();
    }

    @Override
    public OffsetDateTime value6() {
        return getTime();
    }

    @Override
    public TimeOutRecord value1(OffsetDateTime value) {
        setDuration(value);
        return this;
    }

    @Override
    public TimeOutRecord value2(String value) {
        setReason(value);
        return this;
    }

    @Override
    public TimeOutRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public TimeOutRecord value4(String value) {
        setGuildId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public TimeOutRecord value5(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TimeOutRecord value6(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public TimeOutRecord values(OffsetDateTime value1, String value2, String value3, String value4, Long value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
