/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables.records;


import io.github.yusufsdiscordbot.mystigurdian.db.tables.UserIslamicInfoSettings;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserIslamicInfoSettingsRecord extends UpdatableRecordImpl<UserIslamicInfoSettingsRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_islamic_info_settings.user_id</code>.
     */
    public UserIslamicInfoSettingsRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_islamic_info_settings.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.user_islamic_info_settings.quran_reciter_id</code>.
     */
    public UserIslamicInfoSettingsRecord setQuranReciterId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.user_islamic_info_settings.quran_reciter_id</code>.
     */
    public Long getQuranReciterId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_islamic_info_settings.islamic_school</code>.
     */
    public UserIslamicInfoSettingsRecord setIslamicSchool(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_islamic_info_settings.islamic_school</code>.
     */
    public String getIslamicSchool() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS.USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS.QURAN_RECITER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS.ISLAMIC_SCHOOL;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public Long component2() {
        return getQuranReciterId();
    }

    @Override
    public String component3() {
        return getIslamicSchool();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public Long value2() {
        return getQuranReciterId();
    }

    @Override
    public String value3() {
        return getIslamicSchool();
    }

    @Override
    public UserIslamicInfoSettingsRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserIslamicInfoSettingsRecord value2(Long value) {
        setQuranReciterId(value);
        return this;
    }

    @Override
    public UserIslamicInfoSettingsRecord value3(String value) {
        setIslamicSchool(value);
        return this;
    }

    @Override
    public UserIslamicInfoSettingsRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserIslamicInfoSettingsRecord
     */
    public UserIslamicInfoSettingsRecord() {
        super(UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS);
    }

    /**
     * Create a detached, initialised UserIslamicInfoSettingsRecord
     */
    public UserIslamicInfoSettingsRecord(Long userId, Long quranReciterId, String islamicSchool) {
        super(UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS);

        setUserId(userId);
        setQuranReciterId(quranReciterId);
        setIslamicSchool(islamicSchool);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserIslamicInfoSettingsRecord
     */
    public UserIslamicInfoSettingsRecord(io.github.yusufsdiscordbot.mystigurdian.db.tables.pojos.UserIslamicInfoSettings value) {
        super(UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS);

        if (value != null) {
            setUserId(value.getUserId());
            setQuranReciterId(value.getQuranReciterId());
            setIslamicSchool(value.getIslamicSchool());
            resetChangedOnNotNull();
        }
    }
}
