/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables;


import io.github.yusufsdiscordbot.mystigurdian.db.Keys;
import io.github.yusufsdiscordbot.mystigurdian.db.Public;
import io.github.yusufsdiscordbot.mystigurdian.db.tables.records.AmountOfBansRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmountOfBans extends TableImpl<AmountOfBansRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.amount_of_bans</code>
     */
    public static final AmountOfBans AMOUNT_OF_BANS = new AmountOfBans();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmountOfBansRecord> getRecordType() {
        return AmountOfBansRecord.class;
    }

    /**
     * The column <code>public.amount_of_bans.user_id</code>.
     */
    public final TableField<AmountOfBansRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.amount_of_bans.guild_id</code>.
     */
    public final TableField<AmountOfBansRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.amount_of_bans.id</code>.
     */
    public final TableField<AmountOfBansRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.amount_of_bans.amount_of_bans</code>.
     */
    public final TableField<AmountOfBansRecord, Integer> AMOUNT_OF_BANS_ = createField(DSL.name("amount_of_bans"), SQLDataType.INTEGER, this, "");

    private AmountOfBans(Name alias, Table<AmountOfBansRecord> aliased) {
        this(alias, aliased, null);
    }

    private AmountOfBans(Name alias, Table<AmountOfBansRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.amount_of_bans</code> table reference
     */
    public AmountOfBans(String alias) {
        this(DSL.name(alias), AMOUNT_OF_BANS);
    }

    /**
     * Create an aliased <code>public.amount_of_bans</code> table reference
     */
    public AmountOfBans(Name alias) {
        this(alias, AMOUNT_OF_BANS);
    }

    /**
     * Create a <code>public.amount_of_bans</code> table reference
     */
    public AmountOfBans() {
        this(DSL.name("amount_of_bans"), null);
    }

    public <O extends Record> AmountOfBans(Table<O> child, ForeignKey<O, AmountOfBansRecord> key) {
        super(child, key, AMOUNT_OF_BANS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AmountOfBansRecord> getPrimaryKey() {
        return Keys.PK_AMOUNT_OF_BANS;
    }

    @Override
    public List<UniqueKey<AmountOfBansRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_AMOUNT_OF_BANS);
    }

    @Override
    public AmountOfBans as(String alias) {
        return new AmountOfBans(DSL.name(alias), this);
    }

    @Override
    public AmountOfBans as(Name alias) {
        return new AmountOfBans(alias, this);
    }

    @Override
    public AmountOfBans as(Table<?> alias) {
        return new AmountOfBans(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfBans rename(String name) {
        return new AmountOfBans(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfBans rename(Name name) {
        return new AmountOfBans(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmountOfBans rename(Table<?> name) {
        return new AmountOfBans(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Long, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super String, ? super Long, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super String, ? super Long, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
