/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db;


import io.github.yusufsdiscordbot.mystigurdian.db.tables.ReloadAudit;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.reload_audit</code>.
     */
    public static final ReloadAudit RELOAD_AUDIT = ReloadAudit.RELOAD_AUDIT;
}
