/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables.records;


import io.github.yusufsdiscordbot.mystiguardian.db.tables.AmountOfBans;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmountOfBansRecord extends UpdatableRecordImpl<AmountOfBansRecord> implements Record4<Long, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.amount_of_bans.id</code>.
     */
    public AmountOfBansRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.amount_of_bans.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.amount_of_bans.guild_id</code>.
     */
    public AmountOfBansRecord setGuildId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.amount_of_bans.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.amount_of_bans.user_id</code>.
     */
    public AmountOfBansRecord setUserId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.amount_of_bans.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.amount_of_bans.amount_of_bans</code>.
     */
    public AmountOfBansRecord setAmountOfBans(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.amount_of_bans.amount_of_bans</code>.
     */
    public Integer getAmountOfBans() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AmountOfBans.AMOUNT_OF_BANS.ID;
    }

    @Override
    public Field<String> field2() {
        return AmountOfBans.AMOUNT_OF_BANS.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return AmountOfBans.AMOUNT_OF_BANS.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return AmountOfBans.AMOUNT_OF_BANS.AMOUNT_OF_BANS_;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getAmountOfBans();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getAmountOfBans();
    }

    @Override
    public AmountOfBansRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AmountOfBansRecord value2(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public AmountOfBansRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public AmountOfBansRecord value4(Integer value) {
        setAmountOfBans(value);
        return this;
    }

    @Override
    public AmountOfBansRecord values(Long value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AmountOfBansRecord
     */
    public AmountOfBansRecord() {
        super(AmountOfBans.AMOUNT_OF_BANS);
    }

    /**
     * Create a detached, initialised AmountOfBansRecord
     */
    public AmountOfBansRecord(Long id, String guildId, String userId, Integer amountOfBans) {
        super(AmountOfBans.AMOUNT_OF_BANS);

        setId(id);
        setGuildId(guildId);
        setUserId(userId);
        setAmountOfBans(amountOfBans);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AmountOfBansRecord
     */
    public AmountOfBansRecord(io.github.yusufsdiscordbot.mystiguardian.db.tables.pojos.AmountOfBans value) {
        super(AmountOfBans.AMOUNT_OF_BANS);

        if (value != null) {
            setId(value.getId());
            setGuildId(value.getGuildId());
            setUserId(value.getUserId());
            setAmountOfBans(value.getAmountOfBans());
            resetChangedOnNotNull();
        }
    }
}
