/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables.records;


import io.github.yusufsdiscordbot.mystiguardian.db.tables.Kick;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KickRecord extends UpdatableRecordImpl<KickRecord> implements Record5<Long, String, String, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.kick.id</code>.
     */
    public KickRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.kick.guild_id</code>.
     */
    public KickRecord setGuildId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.kick.user_id</code>.
     */
    public KickRecord setUserId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.kick.reason</code>.
     */
    public KickRecord setReason(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.reason</code>.
     */
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.kick.time</code>.
     */
    public KickRecord setTime(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.kick.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Kick.KICK.ID;
    }

    @Override
    public Field<String> field2() {
        return Kick.KICK.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return Kick.KICK.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return Kick.KICK.REASON;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Kick.KICK.TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getReason();
    }

    @Override
    public OffsetDateTime component5() {
        return getTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getReason();
    }

    @Override
    public OffsetDateTime value5() {
        return getTime();
    }

    @Override
    public KickRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public KickRecord value2(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public KickRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public KickRecord value4(String value) {
        setReason(value);
        return this;
    }

    @Override
    public KickRecord value5(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public KickRecord values(Long value1, String value2, String value3, String value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KickRecord
     */
    public KickRecord() {
        super(Kick.KICK);
    }

    /**
     * Create a detached, initialised KickRecord
     */
    public KickRecord(Long id, String guildId, String userId, String reason, OffsetDateTime time) {
        super(Kick.KICK);

        setId(id);
        setGuildId(guildId);
        setUserId(userId);
        setReason(reason);
        setTime(time);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised KickRecord
     */
    public KickRecord(io.github.yusufsdiscordbot.mystiguardian.db.tables.pojos.Kick value) {
        super(Kick.KICK);

        if (value != null) {
            setId(value.getId());
            setGuildId(value.getGuildId());
            setUserId(value.getUserId());
            setReason(value.getReason());
            setTime(value.getTime());
            resetChangedOnNotNull();
        }
    }
}
