/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables.records;


import io.github.yusufsdiscordbot.mystiguardian.db.tables.Oauth;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OauthRecord extends UpdatableRecordImpl<OauthRecord> implements Record6<Long, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.oauth.id</code>.
     */
    public OauthRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.oauth.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.oauth.user_id</code>.
     */
    public OauthRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.oauth.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.oauth.access_token</code>.
     */
    public OauthRecord setAccessToken(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.oauth.access_token</code>.
     */
    public String getAccessToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.oauth.refresh_token</code>.
     */
    public OauthRecord setRefreshToken(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.oauth.refresh_token</code>.
     */
    public String getRefreshToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.oauth.expires_in</code>.
     */
    public OauthRecord setExpiresIn(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.oauth.expires_in</code>.
     */
    public String getExpiresIn() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.oauth.user_json</code>.
     */
    public OauthRecord setUserJson(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.oauth.user_json</code>.
     */
    public String getUserJson() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Oauth.OAUTH.ID;
    }

    @Override
    public Field<String> field2() {
        return Oauth.OAUTH.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Oauth.OAUTH.ACCESS_TOKEN;
    }

    @Override
    public Field<String> field4() {
        return Oauth.OAUTH.REFRESH_TOKEN;
    }

    @Override
    public Field<String> field5() {
        return Oauth.OAUTH.EXPIRES_IN;
    }

    @Override
    public Field<String> field6() {
        return Oauth.OAUTH.USER_JSON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getAccessToken();
    }

    @Override
    public String component4() {
        return getRefreshToken();
    }

    @Override
    public String component5() {
        return getExpiresIn();
    }

    @Override
    public String component6() {
        return getUserJson();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getAccessToken();
    }

    @Override
    public String value4() {
        return getRefreshToken();
    }

    @Override
    public String value5() {
        return getExpiresIn();
    }

    @Override
    public String value6() {
        return getUserJson();
    }

    @Override
    public OauthRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public OauthRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public OauthRecord value3(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public OauthRecord value4(String value) {
        setRefreshToken(value);
        return this;
    }

    @Override
    public OauthRecord value5(String value) {
        setExpiresIn(value);
        return this;
    }

    @Override
    public OauthRecord value6(String value) {
        setUserJson(value);
        return this;
    }

    @Override
    public OauthRecord values(Long value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OauthRecord
     */
    public OauthRecord() {
        super(Oauth.OAUTH);
    }

    /**
     * Create a detached, initialised OauthRecord
     */
    public OauthRecord(Long id, String userId, String accessToken, String refreshToken, String expiresIn, String userJson) {
        super(Oauth.OAUTH);

        setId(id);
        setUserId(userId);
        setAccessToken(accessToken);
        setRefreshToken(refreshToken);
        setExpiresIn(expiresIn);
        setUserJson(userJson);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OauthRecord
     */
    public OauthRecord(io.github.yusufsdiscordbot.mystiguardian.db.tables.pojos.Oauth value) {
        super(Oauth.OAUTH);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setAccessToken(value.getAccessToken());
            setRefreshToken(value.getRefreshToken());
            setExpiresIn(value.getExpiresIn());
            setUserJson(value.getUserJson());
            resetChangedOnNotNull();
        }
    }
}
