/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables.records;


import io.github.yusufsdiscordbot.mystiguardian.db.tables.ReloadAudit;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReloadAuditRecord extends UpdatableRecordImpl<ReloadAuditRecord> implements Record4<Long, String, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reload_audit.id</code>.
     */
    public ReloadAuditRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.reload_audit.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reload_audit.user_id</code>.
     */
    public ReloadAuditRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.reload_audit.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.reload_audit.reason</code>.
     */
    public ReloadAuditRecord setReason(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.reload_audit.reason</code>.
     */
    public String getReason() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.reload_audit.time</code>.
     */
    public ReloadAuditRecord setTime(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.reload_audit.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ReloadAudit.RELOAD_AUDIT.ID;
    }

    @Override
    public Field<String> field2() {
        return ReloadAudit.RELOAD_AUDIT.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return ReloadAudit.RELOAD_AUDIT.REASON;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return ReloadAudit.RELOAD_AUDIT.TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getReason();
    }

    @Override
    public OffsetDateTime component4() {
        return getTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getReason();
    }

    @Override
    public OffsetDateTime value4() {
        return getTime();
    }

    @Override
    public ReloadAuditRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ReloadAuditRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public ReloadAuditRecord value3(String value) {
        setReason(value);
        return this;
    }

    @Override
    public ReloadAuditRecord value4(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public ReloadAuditRecord values(Long value1, String value2, String value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReloadAuditRecord
     */
    public ReloadAuditRecord() {
        super(ReloadAudit.RELOAD_AUDIT);
    }

    /**
     * Create a detached, initialised ReloadAuditRecord
     */
    public ReloadAuditRecord(Long id, String userId, String reason, OffsetDateTime time) {
        super(ReloadAudit.RELOAD_AUDIT);

        setId(id);
        setUserId(userId);
        setReason(reason);
        setTime(time);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReloadAuditRecord
     */
    public ReloadAuditRecord(io.github.yusufsdiscordbot.mystiguardian.db.tables.pojos.ReloadAudit value) {
        super(ReloadAudit.RELOAD_AUDIT);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setReason(value.getReason());
            setTime(value.getTime());
            resetChangedOnNotNull();
        }
    }
}
