/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables.records;


import io.github.yusufsdiscordbot.mystiguardian.db.tables.StoredFiles;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoredFilesRecord extends UpdatableRecordImpl<StoredFilesRecord> implements Record8<Long, String, String, String, String, String, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.stored_files.id</code>.
     */
    public StoredFilesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.stored_files.guild_id</code>.
     */
    public StoredFilesRecord setGuildId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.stored_files.file_name</code>.
     */
    public StoredFilesRecord setFileName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.file_name</code>.
     */
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.stored_files.file_type</code>.
     */
    public StoredFilesRecord setFileType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.file_type</code>.
     */
    public String getFileType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.stored_files.description</code>.
     */
    public StoredFilesRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.stored_files.file_url</code>.
     */
    public StoredFilesRecord setFileUrl(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.file_url</code>.
     */
    public String getFileUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.stored_files.uploaded_by</code>.
     */
    public StoredFilesRecord setUploadedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.stored_files.uploaded_at</code>.
     */
    public StoredFilesRecord setUploadedAt(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.stored_files.uploaded_at</code>.
     */
    public OffsetDateTime getUploadedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, String, String, String, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, String, String, String, String, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StoredFiles.STORED_FILES.ID;
    }

    @Override
    public Field<String> field2() {
        return StoredFiles.STORED_FILES.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return StoredFiles.STORED_FILES.FILE_NAME;
    }

    @Override
    public Field<String> field4() {
        return StoredFiles.STORED_FILES.FILE_TYPE;
    }

    @Override
    public Field<String> field5() {
        return StoredFiles.STORED_FILES.DESCRIPTION;
    }

    @Override
    public Field<String> field6() {
        return StoredFiles.STORED_FILES.FILE_URL;
    }

    @Override
    public Field<String> field7() {
        return StoredFiles.STORED_FILES.UPLOADED_BY;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return StoredFiles.STORED_FILES.UPLOADED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getFileName();
    }

    @Override
    public String component4() {
        return getFileType();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public String component6() {
        return getFileUrl();
    }

    @Override
    public String component7() {
        return getUploadedBy();
    }

    @Override
    public OffsetDateTime component8() {
        return getUploadedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getFileName();
    }

    @Override
    public String value4() {
        return getFileType();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public String value6() {
        return getFileUrl();
    }

    @Override
    public String value7() {
        return getUploadedBy();
    }

    @Override
    public OffsetDateTime value8() {
        return getUploadedAt();
    }

    @Override
    public StoredFilesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StoredFilesRecord value2(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public StoredFilesRecord value3(String value) {
        setFileName(value);
        return this;
    }

    @Override
    public StoredFilesRecord value4(String value) {
        setFileType(value);
        return this;
    }

    @Override
    public StoredFilesRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public StoredFilesRecord value6(String value) {
        setFileUrl(value);
        return this;
    }

    @Override
    public StoredFilesRecord value7(String value) {
        setUploadedBy(value);
        return this;
    }

    @Override
    public StoredFilesRecord value8(OffsetDateTime value) {
        setUploadedAt(value);
        return this;
    }

    @Override
    public StoredFilesRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoredFilesRecord
     */
    public StoredFilesRecord() {
        super(StoredFiles.STORED_FILES);
    }

    /**
     * Create a detached, initialised StoredFilesRecord
     */
    public StoredFilesRecord(Long id, String guildId, String fileName, String fileType, String description, String fileUrl, String uploadedBy, OffsetDateTime uploadedAt) {
        super(StoredFiles.STORED_FILES);

        setId(id);
        setGuildId(guildId);
        setFileName(fileName);
        setFileType(fileType);
        setDescription(description);
        setFileUrl(fileUrl);
        setUploadedBy(uploadedBy);
        setUploadedAt(uploadedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StoredFilesRecord
     */
    public StoredFilesRecord(io.github.yusufsdiscordbot.mystiguardian.db.tables.pojos.StoredFiles value) {
        super(StoredFiles.STORED_FILES);

        if (value != null) {
            setId(value.getId());
            setGuildId(value.getGuildId());
            setFileName(value.getFileName());
            setFileType(value.getFileType());
            setDescription(value.getDescription());
            setFileUrl(value.getFileUrl());
            setUploadedBy(value.getUploadedBy());
            setUploadedAt(value.getUploadedAt());
            resetChangedOnNotNull();
        }
    }
}
