/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmountOfBans implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String userId;
    private final String guildId;
    private final Long id;
    private final Integer amountOfBans;

    public AmountOfBans(AmountOfBans value) {
        this.userId = value.userId;
        this.guildId = value.guildId;
        this.id = value.id;
        this.amountOfBans = value.amountOfBans;
    }

    public AmountOfBans(
        String userId,
        String guildId,
        Long id,
        Integer amountOfBans
    ) {
        this.userId = userId;
        this.guildId = guildId;
        this.id = id;
        this.amountOfBans = amountOfBans;
    }

    /**
     * Getter for <code>public.amount_of_bans.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.amount_of_bans.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.amount_of_bans.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.amount_of_bans.amount_of_bans</code>.
     */
    public Integer getAmountOfBans() {
        return this.amountOfBans;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AmountOfBans other = (AmountOfBans) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.guildId == null) {
            if (other.guildId != null)
                return false;
        }
        else if (!this.guildId.equals(other.guildId))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.amountOfBans == null) {
            if (other.amountOfBans != null)
                return false;
        }
        else if (!this.amountOfBans.equals(other.amountOfBans))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.guildId == null) ? 0 : this.guildId.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.amountOfBans == null) ? 0 : this.amountOfBans.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AmountOfBans (");

        sb.append(userId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(id);
        sb.append(", ").append(amountOfBans);

        sb.append(")");
        return sb.toString();
    }
}
