/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auth implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String accessToken;
    private final String refreshToken;
    private final Long expiresAt;
    private final String userId;
    private final Long id;

    public Auth(Auth value) {
        this.accessToken = value.accessToken;
        this.refreshToken = value.refreshToken;
        this.expiresAt = value.expiresAt;
        this.userId = value.userId;
        this.id = value.id;
    }

    public Auth(
        String accessToken,
        String refreshToken,
        Long expiresAt,
        String userId,
        Long id
    ) {
        this.accessToken = accessToken;
        this.refreshToken = refreshToken;
        this.expiresAt = expiresAt;
        this.userId = userId;
        this.id = id;
    }

    /**
     * Getter for <code>public.auth.access_token</code>.
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Getter for <code>public.auth.refresh_token</code>.
     */
    public String getRefreshToken() {
        return this.refreshToken;
    }

    /**
     * Getter for <code>public.auth.expires_at</code>.
     */
    public Long getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Getter for <code>public.auth.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.auth.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Auth other = (Auth) obj;
        if (this.accessToken == null) {
            if (other.accessToken != null)
                return false;
        }
        else if (!this.accessToken.equals(other.accessToken))
            return false;
        if (this.refreshToken == null) {
            if (other.refreshToken != null)
                return false;
        }
        else if (!this.refreshToken.equals(other.refreshToken))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.accessToken == null) ? 0 : this.accessToken.hashCode());
        result = prime * result + ((this.refreshToken == null) ? 0 : this.refreshToken.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Auth (");

        sb.append(accessToken);
        sb.append(", ").append(refreshToken);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(userId);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
