/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auth implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final byte[] authClass;

    public Auth(Auth value) {
        this.id = value.id;
        this.authClass = value.authClass;
    }

    public Auth(
        Long id,
        byte[] authClass
    ) {
        this.id = id;
        this.authClass = authClass;
    }

    /**
     * Getter for <code>public.auth.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.auth.auth_class</code>.
     */
    public byte[] getAuthClass() {
        return this.authClass;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Auth other = (Auth) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.authClass == null) {
            if (other.authClass != null)
                return false;
        }
        else if (!Arrays.equals(this.authClass, other.authClass))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.authClass == null) ? 0 : Arrays.hashCode(this.authClass));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Auth (");

        sb.append(id);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
