/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystigurdian.db.tables;


import io.github.yusufsdiscordbot.mystigurdian.db.Public;
import io.github.yusufsdiscordbot.mystigurdian.db.tables.records.TimeOutRecord;

import java.time.OffsetDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TimeOut extends TableImpl<TimeOutRecord> {

    /**
     * The reference instance of <code>public.time_out</code>
     */
    public static final TimeOut TIME_OUT = new TimeOut();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>public.time_out.duration</code>.
     */
    public final TableField<TimeOutRecord, OffsetDateTime> DURATION = createField(DSL.name("duration"), SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");
    /**
     * The column <code>public.time_out.reason</code>.
     */
    public final TableField<TimeOutRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(256), this, "");
    /**
     * The column <code>public.time_out.user_id</code>.
     */
    public final TableField<TimeOutRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(256), this, "");
    /**
     * The column <code>public.time_out.guild_id</code>.
     */
    public final TableField<TimeOutRecord, String> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.VARCHAR(256), this, "");
    /**
     * The column <code>public.time_out.id</code>.
     */
    public final TableField<TimeOutRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT, this, "");
    /**
     * The column <code>public.time_out.time</code>.
     */
    public final TableField<TimeOutRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    private TimeOut(Name alias, Table<TimeOutRecord> aliased) {
        this(alias, aliased, null);
    }

    private TimeOut(Name alias, Table<TimeOutRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.time_out</code> table reference
     */
    public TimeOut(String alias) {
        this(DSL.name(alias), TIME_OUT);
    }

    /**
     * Create an aliased <code>public.time_out</code> table reference
     */
    public TimeOut(Name alias) {
        this(alias, TIME_OUT);
    }

    /**
     * Create a <code>public.time_out</code> table reference
     */
    public TimeOut() {
        this(DSL.name("time_out"), null);
    }

    public <O extends Record> TimeOut(Table<O> child, ForeignKey<O, TimeOutRecord> key) {
        super(child, key, TIME_OUT);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TimeOutRecord> getRecordType() {
        return TimeOutRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public TimeOut as(String alias) {
        return new TimeOut(DSL.name(alias), this);
    }

    @Override
    public TimeOut as(Name alias) {
        return new TimeOut(alias, this);
    }

    @Override
    public TimeOut as(Table<?> alias) {
        return new TimeOut(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeOut rename(String name) {
        return new TimeOut(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeOut rename(Name name) {
        return new TimeOut(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeOut rename(Table<?> name) {
        return new TimeOut(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<OffsetDateTime, String, String, String, Long, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super OffsetDateTime, ? super String, ? super String, ? super String, ? super Long, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super OffsetDateTime, ? super String, ? super String, ? super String, ? super Long, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
