/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditChannel implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String guildId;
    private final String channelId;

    public AuditChannel(AuditChannel value) {
        this.guildId = value.guildId;
        this.channelId = value.channelId;
    }

    public AuditChannel(
        String guildId,
        String channelId
    ) {
        this.guildId = guildId;
        this.channelId = channelId;
    }

    /**
     * Getter for <code>public.audit_channel.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.audit_channel.channel_id</code>.
     */
    public String getChannelId() {
        return this.channelId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AuditChannel other = (AuditChannel) obj;
        if (this.guildId == null) {
            if (other.guildId != null)
                return false;
        }
        else if (!this.guildId.equals(other.guildId))
            return false;
        if (this.channelId == null) {
            if (other.channelId != null)
                return false;
        }
        else if (!this.channelId.equals(other.channelId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.guildId == null) ? 0 : this.guildId.hashCode());
        result = prime * result + ((this.channelId == null) ? 0 : this.channelId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuditChannel (");

        sb.append(guildId);
        sb.append(", ").append(channelId);

        sb.append(")");
        return sb.toString();
    }
}
