/*
 * This file is generated by jOOQ.
 */
package io.github.yusufsdiscordbot.mystiguardian.db.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoredFiles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String guildId;
    private final String fileName;
    private final String fileType;
    private final String description;
    private final String fileUrl;
    private final String uploadedBy;
    private final OffsetDateTime uploadedAt;

    public StoredFiles(StoredFiles value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.fileName = value.fileName;
        this.fileType = value.fileType;
        this.description = value.description;
        this.fileUrl = value.fileUrl;
        this.uploadedBy = value.uploadedBy;
        this.uploadedAt = value.uploadedAt;
    }

    public StoredFiles(
        Long id,
        String guildId,
        String fileName,
        String fileType,
        String description,
        String fileUrl,
        String uploadedBy,
        OffsetDateTime uploadedAt
    ) {
        this.id = id;
        this.guildId = guildId;
        this.fileName = fileName;
        this.fileType = fileType;
        this.description = description;
        this.fileUrl = fileUrl;
        this.uploadedBy = uploadedBy;
        this.uploadedAt = uploadedAt;
    }

    /**
     * Getter for <code>public.stored_files.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.stored_files.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.stored_files.file_name</code>.
     */
    public String getFileName() {
        return this.fileName;
    }

    /**
     * Getter for <code>public.stored_files.file_type</code>.
     */
    public String getFileType() {
        return this.fileType;
    }

    /**
     * Getter for <code>public.stored_files.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.stored_files.file_url</code>.
     */
    public String getFileUrl() {
        return this.fileUrl;
    }

    /**
     * Getter for <code>public.stored_files.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return this.uploadedBy;
    }

    /**
     * Getter for <code>public.stored_files.uploaded_at</code>.
     */
    public OffsetDateTime getUploadedAt() {
        return this.uploadedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StoredFiles other = (StoredFiles) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.guildId == null) {
            if (other.guildId != null)
                return false;
        }
        else if (!this.guildId.equals(other.guildId))
            return false;
        if (this.fileName == null) {
            if (other.fileName != null)
                return false;
        }
        else if (!this.fileName.equals(other.fileName))
            return false;
        if (this.fileType == null) {
            if (other.fileType != null)
                return false;
        }
        else if (!this.fileType.equals(other.fileType))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.fileUrl == null) {
            if (other.fileUrl != null)
                return false;
        }
        else if (!this.fileUrl.equals(other.fileUrl))
            return false;
        if (this.uploadedBy == null) {
            if (other.uploadedBy != null)
                return false;
        }
        else if (!this.uploadedBy.equals(other.uploadedBy))
            return false;
        if (this.uploadedAt == null) {
            if (other.uploadedAt != null)
                return false;
        }
        else if (!this.uploadedAt.equals(other.uploadedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.guildId == null) ? 0 : this.guildId.hashCode());
        result = prime * result + ((this.fileName == null) ? 0 : this.fileName.hashCode());
        result = prime * result + ((this.fileType == null) ? 0 : this.fileType.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.fileUrl == null) ? 0 : this.fileUrl.hashCode());
        result = prime * result + ((this.uploadedBy == null) ? 0 : this.uploadedBy.hashCode());
        result = prime * result + ((this.uploadedAt == null) ? 0 : this.uploadedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoredFiles (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(fileName);
        sb.append(", ").append(fileType);
        sb.append(", ").append(description);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(uploadedBy);
        sb.append(", ").append(uploadedAt);

        sb.append(")");
        return sb.toString();
    }
}
